"use client";
import "./globals.css";
import React, { use } from "react";
import { translationService } from "./utils/translations";

export const metadata = {
  title: "Tigre Hacks",
  description: "Generated by create next app",
  icon: "./tiger.png",
};

const TranslationContext = React.createContext();

const TranslationContextProvider = (props) => {
  const [language, setLanguage] = React.useState(translationService.language);

  const changeLanguage = async (language) => {
    await translationService.changeLanguage(language);
    setLanguage(translationService.language);
  };

  const loadLanguage = async () => {
    await translationService.loadLanguage();
    changeLanguage(translationService.language);
  };

  React.useEffect(() => {
    loadLanguage();
  },[]);

  return (
    <TranslationContext.Provider
      value={{
        language: language,
        setLanguage: changeLanguage,
        loadLanguage: loadLanguage,
      }}
    >
      {props.children}
    </TranslationContext.Provider>
  );
};

export const useTranslationContext = () => React.useContext(TranslationContext);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TranslationContextProvider>{children}</TranslationContextProvider>
      </body>
    </html>
  );
}
