import './globals.css'

export const metadata = {
  title: 'Tigre Hacks',
  description: 'Generated by create next app',
  icon:'./tiger.png',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
