export class User {
  name;
  lastname;
  email;
  phoneNumber;
  pronouns;
  gender;
  genderSpecification;
  age;
  cvUrl;
  university;
  universitySpecification;
  dietRestricions;
  dietSpecifications;
  shirtSize;
  identifyAsGroup;
  race;
  raceSpecification;
  maxStudies;
  mainStudyArea;
  mainStudyAreaSpecification;
  agreesToConductCode;
  agreesToShareInfo;
  agreesToSendMail;
}
